### ISSUE TITLE
Penambahan cemilan

### ISSUE THREAD

**Issue by sangmadesu** [sangmadesu/eat-with-me#1]

**Comment by Weabss** [comment]
bro, ane mau konstribusi nih

**Comment by laodealfian** [comment]
bro saya bisa kontribusi ini... tapii komiu mau bayar  berapa saya?

**Comment by sangmadesu** [comment]
oke silahkan kontribusi, tapi ingat harus bikin branch baru ya...

**Comment by llYusufll** [comment]
ane juga mau kontribusi
